### ISSUE TITLE
Kaputter Link ins Müncher Wiki: Bitte Fixen!!!

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-webseite#103]
Hallo zusammen,

auf eurer Homepage funktioniert folgender Link nicht mehr.

https://ffmuc.net/wiki/p/VPN_Offloader#Offloader_mit_Siemens_Futro_S550

Er ist verknüpft bei: https://ffbsee.net/anleitung/router/#komplex
Blauer Button "Freifunk Offloader".
Bitte wieder richtig verknüpfen.
Besten Dank.

Grüße,
Paul

**Comment by re4jh** [comment]
Fix incoming:
>> https://github.com/ffbsee/ffbsee-webseite/pull/104

**Comment by DO1JLR** [comment]
thanks
