### ISSUE TITLE
Featurerequest: Layout als Theme

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-webseite#117]
Weil mehrere Seite (FFBSee, FFNBSee,...) das mehr oder weniger gleiche Layout verwenden, wäre es ganz cool das layout als eigenständiges Theme zu haben!

https://www.getlektor.com/docs/themes/

Und am besten auch direkt bei FFBSee und FFNBSee einfügen!

**Comment by rtt-mmk** [comment]
"Lektor theme support is new. It should be considered unstable and could change in the future." - vielleicht sollte man damit noch die nächste Lektor-Version abwarten?

**Comment by DO1JLR** [comment]
@rtt-mmk Was noch viele Jahre dauern wird (falls das passiert) weil Lektro nicht mehr in aktivier Entwicklung ist.
