### ISSUE TITLE
(Possible/definitive) misbrauch von adminrechten!

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-webseite#120]
Der commit c273dd065da20a8505f28c7042ed50b910f302c2 von @xperimental wurde ohne absprache oder 4-Augen prinzip auf den master-branch gepushed.

Er enthält änderungen, die es verhindern, das commits der Webseite auf korrekte syntax getestet werden, die nicht auf den masterbranch gehen.

Das ist eine änderung, die man zumindest in einer diskussion im Pull-Request besprechen müsste.

Ich fordere die Aufgabe der adminrechte von @xperimental!!

**Comment by xperimental** [comment]
Hello @DO1JLR, thanks for your comment. I did multiple changes during the weekend on both websites of ffbsee and was in direct contact with other people (most notably @mart-ffbsee ) during that time. I had also asked him if it was okay for him if I try something directly on master before doing the change, because I was not sure if it worked on the first try.

While this did technically not satisfy our constraint to have pull-requests, I and apparently also the others deemed this okay in this case. But I am open to hearing other opinions as well.

As for your comment that the change would stop changes being tested before they appear on the website, this is not correct. While the "branch builds" now only happen for master, there are still the "pull request builds". Before we had both of them at the same time, which I considered wasteful. I have also commented this on the commit you mentioned by now to avoid confusion.

**Comment by DO1JLR** [comment]
Mart hält sich also nicht an die von ihm selber initiierten und unterschriebenen Community-Richtlinien?
Kann das wer bestätigen?

Bei technischen Fragen gäbe es viele Orte an die man sich wenden kann. Oder man missbraucht seine adminprivilegien *(angeblich abgesprochen, aber nicht im public chat/mailingliste, also nicht nachweißbar)*. Oder man wendet sich beispielsweise an die [top-contributers](https://github.com/ffbsee/ffbsee-webseite/graphs/contributors) des Repos oder die jenigen, die die travis integration ( /59f8ec1bf37985d67397878df5ec566cc157fae9#diff-354f30a63fb0907d4ad57269548329e3 ) hinzugefügt haben!

Bitte gebe deine adminrechte ab und halte dich zukünftig an die community guidlines oder wir halten uns alle nicht mehr dran!

**Comment by mart-ffbsee** [comment]
Also dann mal ein paar Antworten:
1. Die Community-Guidelines gibt es momentan nur als Entwurf, den bisher nur wenige Leute kennen/mitgestaltet haben. Diese Guidelines sollen aber möglichst von einem großen Teil der Community abgesegnet werden, was Ende dieser Woche zumindest von Seiten des Fördervereins (und da wird ja hoffentlich ein Großteil der aktiven Community anwesend sein) geschehen soll.
Alle jetzt hier fraglichen Änderungen (die selbstverständlich in einem Git-Repo niemals final sind), hatten das Ziel, dass das Autodeploy wieder funktioniert, damit der Termin für genau dieses Treffen auf der Webseite steht. Da Du mehrmals sagtest, dass Du vor dem "Geekend" im April  nichts "an Freifunk" machen möchtest, mussten halt andere Leute etwas ausprobieren, wie gut oder schlecht auch immer diese Lösung sein mag. Wie gesagt erhebt auch keine dieser Änderungen den Anspruch final, oder auch nur irgendwie besonders gut zu sein. Es steht jedem frei, bessere Vorschläge zu machen.
Die ganze Idee der Guidelines ist ja, dass solche angeblichen Regeln, die hier seit einigen Monaten ohne vorherige Absprache einfach so in den Raum gestellt werden, mal besprochen und von einer möglichst breiten Community verabschiedet werden sollen. Nur wenn man irgendwo nachlesen kann, was diese Regeln sind, kann man sich ja überhaupt dran halten. Und ja; ich kenne den Entwurf und täte gut daran, mich vielleicht auch schon jetzt dran zu halten.

2. War es trotzdem eine blöde Idee die Absprache in einem Chat zu machen anstatt hier per PR auf Github?
Ja, das war richtig blöd. Sorry!
Wir hätten das definitiv mit PR und Review machen sollen!

Inhaltlich hättest Du aber das gleiche Ergebnis bekommen, dass Du jetzt mit den Änderungen unzufrieden bist. Bitte zeige uns doch möglichst bald wie man es besser machen würde, oder beteilige Dich an der Diskussion, welche Methode besser ist. Das ganze Thema mit den Guidelines wird ja am kommenden Samstag besprochen. Es steht Dir frei, Dein Anliegen dort in großer Runde vorzubringen. Momentan schreibst Du hier ja eh nur mit genau den zwei Leuten, mit deren Verhalten Du unzufrieden bist.
Dann bis Samstag!

**Comment by DO1JLR** [comment]
Wie ich dir schon privat gesagt hatte bin ich an diesem Samstag terminlich verhindert.
Dass das treffen dort trotzdem statt findet finde ich schade aber du meintest ja es wäre der einzige Termin zu den ihr Vorstände zeit habt. Und da habe ich als nicht-zahlende Person offensichtlich wenig einfluss drauf.

Mir ist der Pull-Request vom Xperimental aufgefallen und auch das der nicht funktioniert. Das war mitten am Wochenende als ich in Zürich war.

Kaum war ich wieder zurück in DE habe ich mir das näher angeschaut und commits auf dem masterbranch festgestellt.

Im Chat bin ich aus offensichtlichen Gründen inaktiv, aber gehe nun - wie versprochen - ganz raus.

**Comment by DO1JLR** [comment]
Das verlassen des Matrix chat stand schon seit ein paar Wochen auf der todo liste und hat nichts mit diesem Issue hier zu tun!

**Comment by mart-ffbsee** [comment]
Okay, zur Kenntnis genommen.

**Comment by mart-ffbsee** [comment]
zu dem thema wurde jetzt anscheinend alles gesagt.
