### ISSUE TITLE
variable needed for github action deployment

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-webseite#122]
Für das deployment der seite via github action wird eine gewisse variable benötigt.

diese bitte umgehend eintragen.

inhalt der variable sollte secret sein, daher nicht hier via issue sondern per DM

**Comment by xperimental** [comment]
I think this can be handled as part of the #121 once we decide whether to switch to Github Actions or not. Closing as duplicate.

**Comment by DO1JLR** [comment]
Nein

#121 beschaeftigt sich exklusiv mit testung. Für deployment wäre - mangrls fehlebden variablen - eine neue action gekommen.
