### ISSUE TITLE
Mehr Menschen dazu bekommen, an der Freifunk Webseite mitzuarbeiten

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-webseite#34]
Die Idee von Freifunk beinhaltet, dass es eine Community von mehr als einer Person gibt. Diese beschäftigt sich gemeinschaftlich mit dem Thema Freifunk und teilt ihr Wissen mit anderen.

Zum Beispiel auf einer Webseite.

Bei Freifunk Bodensee auf dieser Webseite.

Aber da ist schon das Problem:
Früher war die Webseite ein Wiki. Da haben viele Menschen gesagt, dass es total unübersichtlich ist und sie nichts finden. Manchmal gab es auch phasen, da haben sich plötzlich ganz viele Bots angemeldet die automatisiert unerwünschten Inhalt (offensichtliche Werbung, die nichts mit Freifunk zu tun hat) verbreitet hat. Die funktion des Bearbeitens wurde aber kaum genutzt.

Nun gibt es eine neue Webseite. Mit der Hoffnung, dass diese als Übersichtlicher wahrgenommen wird. Mit dem Bereich "Anleitungen" und vielen anderen tollen Bereichen, wo man informationen teilen kann.

Die Seite [Contributors](https://github.com/ffbsee/webseite/graphs/contributors) zeigt recht gut, wie viele Menschen mal einen Tippfehler korrigiert haben und wie viele Menschen eine komplette Anleitungen, einen Blogeintrag oder sonst eine Seite angelegt haben.

Außerdem gibt es die Aussage von Menschen, dass sie das bearbeiten  zu kompliziert finden und nicht verstehen. Andere sagen, dass das alles "0 problem" ist, aber trotzdem kommt einfach nichts.

Das war beim Wiki so. Das ist jetzt so.

Wie kann man das ändern?

**Comment by re4jh** [comment]
Kann Lektor irgendeine Art von Benutzerautentifikation?
Sonst könnte man hier evtl. auch 'nen nginx drüber stülpen, der das übernimmt.
-
Ich will darauf raus, dass der Laie eine rennende Lektorinstanz vorfindet, an der er sich anmelden kann. Das macht das Editieren dann schon mal niedrigschwelliger.
-
Wie wir dann aus den hier fabrizierten Edits schöne einzelne Pull-Requests machen, seht ihr dann nach der nächsten Maus.... ;-)

**Comment by DO1JLR** [comment]
Lektor bietet (soweit ich weiß) da keinerlei Authentifikationsmechanismen.

Wofür auch... Es werden die Dateien lokal geändert und wer das produktiv schalten will, braucht dann direkt den zugriff zum Webserver.
Oder wie hier, hat travis den Zugriff und übernimmt das pushen!

**Comment by re4jh** [comment]
Ich verstehe ja Sinn und Zweck von Versionierung und als Entwickler kann ich das auch bedienen.
Eine gewisse Schwelle stellt das halt dar. Vielleicht wäre ein gewisser Automatisierungsgrad ein Lösungsweg diese Schwelle abzubauen.

Meine rein konzeptionelle Idee war bisher:
Da rennt ein Lektor, bei dem der berechtigte Laie sich authentifizieren kann und nach seinen Edits auf Knopfdruck Commit und Pull-Request auslösen kann.

Andere Vorschläge um mehr Mitarbeit an der Website zu bekommen sind natürlich weiterhin wilkommen.

**Comment by DO1JLR** [comment]
Die idee ein lektor im Freifunk Netz laufen zu haben kommt mir immer sympatischer vor. Dann halt mit entweder sehr einfacher selber gestrickter Management-Oberfläche in der man halt seine änderungen committen und pushen kann und dann jemand von Freifunk (ich [und du?] benachrichtigt wird, dass anzuschauen...

Aber muss halt auch jemand mal bauen...

**Comment by Huster-at-github** [comment]
*nixblick*
Ist das jetzt ein Diskussions-Threasd auf Github oder was?

**Comment by Huster-at-github** [comment]
> 
> 
> Die idee ein lektor im Freifunk Netz laufen zu haben kommt mir immer sympatischer vor. Dann halt mit entweder sehr einfacher selber gestrickter Management-Oberfläche in der man halt seine änderungen committen und pushen kann und dann jemand von Freifunk (ich [und du?] benachrichtigt wird, dass anzuschauen...
> 
> Aber muss halt auch jemand mal bauen...

Lektor kann ich schon machen. Müssen nur die Technik vorher klären.     ;-)

**Comment by DO1JLR** [comment]
Und da wären wir beim Problem...

Es macht halt niemand etwas. Und komm mir jetzt nicht damit, dass das die Vorstände machen müssten!

**Comment by Huster-at-github** [comment]
*lach*
Nix, dann wird das nie was!!! - Das müssen wir selber machen.

**Comment by DO1JLR** [comment]
Sehr gut. Dann mach das doch bitte einfach!
