### ISSUE TITLE
Wie flasht man eine Futro?

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-webseite#35]
Dies ist eine Frage, die unbedingt eine eigene Anleitung braucht.

**Comment by DO1JLR** [comment]
#37

**Comment by Huster-at-github** [comment]
Vielleicht erstmal kurz für die Newbies nen link zu dem Futro, was Du meinst?

**Comment by DO1JLR** [comment]
Ja, nicht die schlechteste Idee... Magst du das nicht als dein ersten Pull-Request hier selber machen?
