### ISSUE TITLE
Standard für den Schreibstil der Webseite

### ISSUE THREAD

**Issue by TalviT** [ffbsee/ffbsee-webseite#54]
Mir ist aufgefallen, dass manche Seiten in einer lockeren, umgänglichen Sprache geschrieben sind, andere sprechen den Leser per Sie an und sind allgemein ziemlich förmlich gehalten.
Wenn viele Leute an der Webseite Inhalte hinzufügen, wäre es gut eine Art Richtwert festzulegen, wie Artikel, Anleitungen, Informationsseiten und so weiter verfasst werden sollten, damit es ein einheitlichen Schreibstil gibt. Auch Dinge wie "schreibt man Freifunk Treffen, Freifunk-Treffen oder Freifunktreffen?" kann man hier mit bedenken.

Um einen Anfang zu machen, würde ich vorschlagen, dass die Seite den Leser durchgängig per Du ansprechen sollte, den lockeren Ton auf Seiten der "die breite Masse" als Zielgruppe hat beizubehalten, diesen aber in den Informationsseiten und Anleitungen, die tiefer in die Technik gehen zu zügeln, sodass der Schreibstil aber noch freundlich und nah am Menschen, also auch nicht übertrieben förmlich oder Handbuchartig ist.

**Comment by DO1JLR** [comment]
Naja, das Problem hier ist ganz einfach das mangelde Interesse und die bereitschaft überhaupt etwas zur Webseite beizutragen.

Also schreibe ich irgendwie etwas, wie es mir gerade in den Sinn kommt.

Klar, wäre das ein gemeinschaftlich gepflegtes Projekt mit mehreren wirklich aktiven Menschen die regelmäßig etwas Beitragen und auch eigene Inhalte schaffen wird das relevant.

Aber so versuche ich halt meistens beim du zu bleiben, ziehe das aber nicht immer durch!

**Comment by DO1JLR** [comment]
>  ... wäre es gut eine Art Richtwert festzulegen, wie Artikel, Anleitungen, Informationsseiten und so weiter verfasst werden sollten...
>
Wo würdest du denn so etwas am liebsten festgehalten sehen?

Als eigene Anleitung auf der Webseite? Als Wiki hier in GitHub? In der README? Als verlinkten Thread auf der Mailingliste?

**Comment by re4jh** [comment]
Oh welch guter Gedanke. Danke @Talvi.

@DO1JLR: Ich bin gegen eine Platzierung der Info (nur) auf der Mailingliste. Da gehts dann unter und ist zu weit weg von der Website.
Am sympatischsten ist mir die Readme hier.

Dann liegt das wie so ne Fußmatte vor der Haustür, bevor der Contributor contributet :-)

**Comment by DO1JLR** [comment]
Ja... dann gerne einfach mal machen @TalviT

**Comment by DO1JLR** [comment]
@TalviT ping?

**Comment by DO1JLR** [comment]
@TalviT ping?

**Comment by Huster-at-github** [comment]
Tendiere auch zum "Du".
Aber mit Auswahlmöglichkeit des "Sie".
Weiß nicht, ob das geht.

**Comment by DO1JLR** [comment]
Was willst du?

**Comment by DO1JLR** [comment]
Okay, nun die Frage: Wer passt die README an?

@talvi @Huster-at-github

**Comment by DO1JLR** [comment]
wegen inaktivität geschlossen :cry:
