### ISSUE TITLE
font awesome icons broken

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffbsee-webseite#74]
Something is not working...

**Comment by maxbachmann** [comment]
Oh gestern vergessen. Schaue ich mir an

**Comment by maxbachmann** [comment]
Ich kenne die Ursache, muss ich aber später lokal testen wenn ich nach Hause komme und der fix kommt dann irgendwann heute Abend .)

**Comment by DO1JLR** [comment]
habs gefixt. war meine schuld! ein space hat gefehlt
