### ISSUE TITLE
841 von router vorschlägen entfernen

### ISSUE THREAD

**Issue by DEvil0000** [ffbsee/ffbsee-webseite#88]
841 von `https://ffbsee.net/anleitung/router/` entfernen.

Gründe:
* neue Hardware revisions unsupported - und das bleibt wohl so
* performance mit max 5Mbit ist schlecht und im mesh nahe 0.
* bei mehr als 2 Clients guckt der dumm
* alter revisions sind nicht erhältlich
* 4MB Flash sind möglicherweise bald unsupported
* Leute kaufen den und gucken dann dumm

**Comment by DO1JLR** [comment]
thanks
